# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/brandonramirez/PycharmProjects/proyectoequipo1/src/HU003/vista/est_electo.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(340, 200)
        MainWindow.setMinimumSize(QtCore.QSize(340, 200))
        MainWindow.setMaximumSize(QtCore.QSize(340, 200))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.estApMat = QtWidgets.QLineEdit(self.centralwidget)
        self.estApMat.setGeometry(QtCore.QRect(140, 130, 181, 21))
        self.estApMat.setStyleSheet("")
        self.estApMat.setMaxLength(255)
        self.estApMat.setObjectName("estApMat")
        self.lblApMat = QtWidgets.QLabel(self.centralwidget)
        self.lblApMat.setGeometry(QtCore.QRect(20, 130, 111, 16))
        self.lblApMat.setObjectName("lblApMat")
        self.estApPat = QtWidgets.QLineEdit(self.centralwidget)
        self.estApPat.setGeometry(QtCore.QRect(140, 100, 181, 21))
        self.estApPat.setStyleSheet("")
        self.estApPat.setMaxLength(255)
        self.estApPat.setObjectName("estApPat")
        self.lblID = QtWidgets.QLabel(self.centralwidget)
        self.lblID.setGeometry(QtCore.QRect(20, 40, 91, 16))
        self.lblID.setObjectName("lblID")
        self.estNombres = QtWidgets.QLineEdit(self.centralwidget)
        self.estNombres.setGeometry(QtCore.QRect(140, 70, 181, 21))
        self.estNombres.setStyleSheet("")
        self.estNombres.setMaxLength(255)
        self.estNombres.setObjectName("estNombres")
        self.lblNombres = QtWidgets.QLabel(self.centralwidget)
        self.lblNombres.setGeometry(QtCore.QRect(20, 70, 71, 16))
        self.lblNombres.setObjectName("lblNombres")
        self.lblApPat = QtWidgets.QLabel(self.centralwidget)
        self.lblApPat.setGeometry(QtCore.QRect(20, 100, 111, 16))
        self.lblApPat.setObjectName("lblApPat")
        self.estID = QtWidgets.QLineEdit(self.centralwidget)
        self.estID.setEnabled(True)
        self.estID.setGeometry(QtCore.QRect(140, 40, 181, 21))
        self.estID.setAutoFillBackground(False)
        self.estID.setStyleSheet("")
        self.estID.setMaxLength(8)
        self.estID.setReadOnly(True)
        self.estID.setObjectName("estID")
        self.lblID_2 = QtWidgets.QLabel(self.centralwidget)
        self.lblID_2.setGeometry(QtCore.QRect(20, 10, 131, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblID_2.setFont(font)
        self.lblID_2.setObjectName("lblID_2")
        self.nestCerrar = QtWidgets.QPushButton(self.centralwidget)
        self.nestCerrar.setGeometry(QtCore.QRect(230, 160, 91, 32))
        self.nestCerrar.setObjectName("nestCerrar")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sorteando..."))
        self.lblApMat.setText(_translate("MainWindow", "Apellido materno:"))
        self.lblID.setText(_translate("MainWindow", "ID estudiante:"))
        self.lblNombres.setText(_translate("MainWindow", "Nombres:"))
        self.lblApPat.setText(_translate("MainWindow", "Apellido paterno:"))
        self.lblID_2.setText(_translate("MainWindow", "Estudiante electo:"))
        self.nestCerrar.setText(_translate("MainWindow", "Cerrar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
